/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  UserGuides: [
    "user",
    "user/faq",
    {
      "User Guides": [
        "user/getting-started",
        "user/installing-modules",
        "user/arcdps-integration",
        "user/multibox-support",
        "user/portable-mode",
        "user/launch-options"
      ],
    },
    {
      "Troubleshooting": [{
        type: 'autogenerated',
        dirName: 'user/troubleshooting'
      }]
    }
  ],
  DevGuides: [
    "dev",
    {
      "Create a Module": [
        "modules/overview/getting-started",
        "modules/overview/update-your-manifest",
        "modules/overview/debugging",
        "modules/overview/anatomy",
        "modules/overview/bhm",
        "modules/overview/release"
      ]
    },
    {
      "Module Citizen": [
        "modules/module-citizen/overview",
        "modules/module-citizen/friendly-ui-ux",
        "modules/module-citizen/ensuring-stability",
        "modules/module-citizen/repo-etiquette"
      ]
    },
    {
      "Guides": [
        "modules/guides/settings",
        "modules/guides/gw2api",
        "modules/guides/graphicsdevice",
        "modules/guides/textures",
        "modules/guides/gw2assets"
      ]
    },
    {
      "API - Controls": [
        "dev/controls/overview",
  
        "dev/controls/colorpicker",
        "dev/controls/detailsbutton",
        "dev/controls/image",
        "dev/controls/label",
        "dev/controls/loadingspinner",
        "dev/controls/panel",
        "dev/controls/standardbutton",
        "dev/controls/standardwindow",
        "dev/controls/tabbedwindow2",
        "dev/controls/textbox"
      ]
    }
  ]
};

module.exports = sidebars;